# Site settings
title: Vishwanath Nagendra's Notes
email: vishykaranth@gmail.com
description: "Vishwanath Nagendra's Notes"
baseurl: ""
url: "https://vishykaranth.github.io"
#twitter_username: vishwa
#github_username:  vishwa

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

